version: '3'

networks:
    web:
        external: true

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file: .env
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${N8N_HOST}"
      traefik.port: '5678'
    expose:
      - "80"
      - "443"
    networks:
      - default
      - web
    volumes:
      -  /opt/n8n/.n8n:/home/node/.n8n
