version: '3'

networks:
    web:
        external: true

services:
  n8n-hiveagile:
    image: n8nio/n8n:${VERSION}
    container_name: n8n-hiveagile
    restart: unless-stopped
    env_file: .env
    labels:
      # Traefik
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${N8N_HOST}"
      traefik.port: '5678'
      # Caddy
      caddy: ${N8N_HOST}
      caddy.reverse_proxy: "{{upstreams 5678}}"
    expose:
      - "80"
      - "443"
    networks:
      - default
      - web
    volumes:
      -  ./docker-volumes/n8n/data:/home/node/.n8n
      - ./bin/trans.sh:/bin/trans.sh
